name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, main]
    paths-ignore:
      - "**.md"
      - "**.rst"

jobs:
  lint-unit:
    uses: canonical/bootstack-actions/.github/workflows/lint-unit.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
    with:
      python-version: ${{ matrix.python-version }}
      tox-version: "<4"
      working-directory: ./src

  func:
    uses: canonical/bootstack-actions/.github/workflows/func.yaml@v3-external-openstack
    needs: lint-unit
    strategy:
      fail-fast: false
    with:
      command: "sleep 86400"
      juju-channel: "3.1/stable"
      nested-containers: false
      provider: "lxd"
      python-version: "3.10"
      timeout-minutes: 120
      tox-version: "<4"
      action-operator: false
      external-controller: true
      runs-on: "['self-hosted', 'runner-advanced-routing-a']"
      zaza-yaml: "LS0tCm1vZGVsX3NldHRpbmdzOgogIGltYWdlLXN0cmVhbTogcmVsZWFzZWQKcmVnaW9uOiBwcm9kc3RhY2s2CmNsb3VkOiBidWlsZGVyLWNsb3VkCmNyZWRlbnRpYWw6IGJ1aWxkZXItY2xvdWQtY3JlZAo="
      pytest-env: "ZXhwb3J0IFBZVEVTVF9DTE9VRF9OQU1FPWJ1aWxkZXItY2xvdWQKZXhwb3J0IFBZVEVTVF9DTE9VRF9SRUdJT049cHJvZHN0YWNrNgpleHBvcnQgUFlURVNUX0NMT1VEX0NSRURFTlRJQUw9YnVpbGRlci1jbG91ZC1jcmVkCg=="
      juju-controller: "soleng-ci-ctrl"
    secrets:
      juju-controllers-yaml: ${{ secrets.JUJU_CONTROLLERS_YAML }}
      juju-accounts-yaml: ${{ secrets.JUJU_ACCOUNTS_YAML }}
